### ISSUE TITLE
09/03 - Team94

### ISSUE THREAD

**Issue by idgm5** [FrancoRosa/library-js#2]
Please add any comments or suggestions here

**Comment by idgm5** [comment]
You can add:

`window.location.reload()`

After each time you save in the local storage, so you can fix the bug of missing targets, in case you're using an index or loop to sort the items.

Good project, I like that you guys spend some time in adding a design even if it wasn't required! :+1:

**Comment by FrancoRosa** [comment]
Thank you, Isaac, 
We solved the problem using a unique _id_, now the search operations relie on the _id_ not on the _index_.
